name: price_list
description: Price List project

publish_to: 'none'


version: 2.0.3+4

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.7
  easy_mask: ^2.0.1
  provider: ^6.0.3
  dropdown_button2: ^1.8.2
  sqflite: ^2.1.0
  intl: ^0.17.0
  permission_handler: ^10.1.0
  auto_size_text: ^3.0.0
  file_picker: ^5.2.1
  path: ^1.8.2
  path_provider: ^2.0.11
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.6
  flutter_automation: ^2.0.0
  persian_number_utility: ^1.1.3

  flutter_launcher_icons: ^0.11.0
  double_back_to_close_app: ^2.1.0











dev_dependencies:
  flutter_test:
    sdk: flutter



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/app_icon.png"


  flutter_lints: ^2.0.0




flutter:
#  generate: true
  uses-material-design: true


  assets:
  - images/




  fonts:
    - family: Helvtica
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: Persian
      fonts:
        - asset: fonts/shabnam.ttf

