name: price_list
description: Price List project

publish_to: 'none'


version: 4.4.4+22

environment:
  sdk: '>=2.18.0-271.4.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
#  currency_text_input_formatter: ^2.1.7
  easy_mask: ^2.0.1
  provider: ^6.0.3
  dropdown_button2: ^2.3.9
  sqflite: ^2.1.0
  intl: ^0.19.0
  permission_handler: ^10.1.0
  auto_size_text: ^3.0.0
  file_picker: ^5.2.1
  path: ^1.8.2
  path_provider: ^2.0.11
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.6
  flutter_automation: ^2.0.0
  persian_number_utility: ^1.1.3
  double_back_to_close_app: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  shared_preferences: ^2.1.0
  blurrycontainer: ^1.0.2
  pdf: ^3.9.0
  open_filex: ^4.3.2
  flutter_launcher_icons: ^0.12.0
  http: ^0.13.6
  image: ^4.1.3
  image_compression_flutter: ^1.0.3
  archive: ^3.4.7
  expandable: ^5.0.1
  flutter_slidable: ^2.0.0
  gap: ^3.0.1
  flutter_animate: ^4.4.0
  lottie: ^2.6.0
#  cafebazaar_flutter: ^1.0.2
  google_fonts: ^4.0.4
  package_info_plus: ^4.2.0
#  bitsdojo_window: ^0.1.5
  share_plus: ^7.2.2
  excel: ^4.0.2
  mobile_scanner: ^4.0.1
#  flutter_poolakey: ^2.2.0
  myket_iap: ^1.1.5
  image_picker: ^1.0.7
  flutter_typeahead: ^4.3.1
  photo_view: ^0.15.0
  currency_text_input_formatter: ^2.2.3





dependency_overrides:
  intl: ^0.19.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  change_app_package_name: ^1.1.0



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
    image_path: "assets/images/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "assets/images/app_icon.png"


  flutter_lints: ^2.0.0




flutter:
#  generate: true
  uses-material-design: true


  assets:
  - assets/images/
  - assets/fonts/
  - assets/animations/
  - assets/files/




  fonts:
    - family: Helvtica
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Shabnam
      fonts:
        - asset: assets/fonts/shabnam.ttf
    - family: Roya
      fonts:
        - asset: assets/fonts/roya.ttf
        - asset: assets/fonts/royab.ttf
    - family: Koodak
      fonts:
        - asset: assets/fonts/koodak.ttf
    - family: Terafik
      fonts:
        - asset: assets/fonts/terafik.ttf
    - family: Titr
      fonts:
        - asset: assets/fonts/titr.ttf
    - family: Elham
      fonts:
        - asset: assets/fonts/elham.ttf
    - family: Sahel
      fonts:
        - asset: assets/fonts/sahel.ttf
        - asset: assets/fonts/sahel-Bold.ttf
    - family: Mitra
      fonts:
        - asset: assets/fonts/mitra.ttf

